services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel

  web:
    image: nginx:stable
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mariadb:10.5
    container_name: laravel-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_dedinat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
